version: '3.6'
services:
  pokedex:
    container_name: ${APP_NAME}
    image: ${APP_NAME}:${APP_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORK_DIR: ${WORK_DIR}
    network_mode: 'host'
    restart: always
    environment: 
      - PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes: 
      - /app/node_modules
      - .:/app